In [8]:
l=[23,323,523,433,3,1,44,-33]

In [9]:
#array has different structure than lists

In [12]:
import numpy as np  # NumPy is the fundamental package for scientific computing

In [13]:
#a powerful N-dimensional array object

#sophisticated (broadcasting) functions

#tools for integrating C/C++ and Fortran code

#useful linear algebra, Fourier transform, and random number capabilities

In [16]:
a=np.array(l)

In [17]:
a

array([ 23, 323, 523, 433,   3,   1,  44, -33])

In [18]:
#array can only have on type for its elements
#arrays also have more function for its object than list

## slicing arrays
----

In [20]:
a[2:] # everything from index 2 to the end

array([523, 433,   3,   1,  44, -33])

In [21]:
a[2:4]

array([523, 433])

In [22]:
# in slicing array you are not creating new array >> you are actually working with view of the same array 
# so  if you make any changing in the new array it will be effected to the original one

In [23]:
c=a.copy()

In [24]:
c #here you will have tottaly different array 

array([ 23, 323, 523, 433,   3,   1,  44, -33])